/// Flutter icons Arrow
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Arrow
///      fonts:
///       - asset: fonts/Arrow.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
library;
import 'package:flutter/widgets.dart';

class Arrow {
  Arrow._();

  static const _kFontFam = 'Arrow';
  static const String? _kFontPkg = null;

  static const IconData arrow_circle_left = IconData(0xf0a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
